# Generated by Django 3.0.3 on 2020-02-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_auto_20200221_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
